### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by r00tsyst3m** [KritixKaung/PSO2-GrindersProMax#1]
it said 999 grinder bought but when i check material storage still 0 grinder

**Comment by KritixKaung** [comment]
Sorry for late reply, I just haven't been playing the game nor using GitHub lately. Anyways this is just AHK script so it doesn't really know if the purchase process is succeeded in the game or not. It just assume everything work fine and notify you about how many grinders are bought if everything work well without error. But the variable hardware and ping to the game server between users can make the script not work and have errors in the process. For my script the timings are really, really tight (around 200ms for in game actions and 500ms~1000ms for server actions) so even little FPS drop or game connection lag can throw the script off to error. You can try increasing those timings in the script to higher values to fix those errors although it will make the process a bit longer. And lastly here's a [link](https://github.com/NatsumeLS/PSO2-AHK-Grinders-Buying-Selling) to a fork from my script that has higher timings and also seems to be being maintained currently.
