### ISSUE TITLE
Make SleepTimer a Variable

### ISSUE THREAD

**Issue by ronelm2000** [KritixKaung/PSO2-GrindersProMax#2]
I've noticed that in your script that you have documented that SleepTimer should be adjusted if you have more latency than 100ms, however, changing all sleep timers in your script is difficult.

Having one as a single variable (SleepTimerFactor = 50) for example would be a good way to edit all SleepTimer values at once.

![image](https://user-images.githubusercontent.com/12634987/117289812-a0753100-ae9f-11eb-98e0-463ae0f98ca2.png)

**Comment by KritixKaung** [comment]
Thanks for suggestion. And yea I thought about it but actually forgot to add that stuff lol. I'll put that and release an update in a bit.
